version: "3"

services:
  strapiapi:
    image: strapi/strapi
    container_name: sunsetlakeview
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      PORT: ${PORT}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
 
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
  db:
    driver: local